### ISSUE TITLE
Issue 1: User can view available weapons in BOTW

### ISSUE THREAD

**Issue by edtan094** [edtan094/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view available weapons in BOTW

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will see a list of weapons from BOTW

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

 
![image](https://user-images.githubusercontent.com/90667339/148291155-05cdfa94-5e3f-4b04-b9e9-1c78790e4e43.png)
![image](https://user-images.githubusercontent.com/90667339/148282198-873a36cf-2a56-4e99-9770-b58af811308f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a div[data-view="home-page"] to the HTML
- [x] Create the heading of the page
- [x] Ensure that the CSS is ready and the container are ready to hold the data from the API.
- [x] Create a variable that will hold all the listed weapons by querying (#weapon-list)
- [x] Create a variable for xhr.
- [x] Add an event listener to the xhr that will load all the data from the API onto the page as soon as the page loads
- [x] Ensure that the page looks nice on both mobile-sized and desktop-sized screens.
- [x] Ensure all items can be viewed by the user by scrolling
- [x] Verify that the weapon elements are within the container and have the appropriate spacing
