### ISSUE TITLE
Issue 2: User can search for a weapon in BOTW

### ISSUE THREAD

**Issue by edtan094** [edtan094/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can search for a weapon in BOTW using the search bar.  

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user prefers to look for a weapon by typing in the name instead of scrolling down the list, they can do so by using the search bar.  The search bar should be able to find any weapon that contains the characters typed into the search bar.  (e.g. typing in "sword" will pop up all items that have the word sword)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90667339/148288772-0fd322ea-2131-4e35-ba2f-c9c78766af80.png)
![image](https://user-images.githubusercontent.com/90667339/148288800-2f087821-949c-402b-8094-bd1b12ef67f0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a form search bar with the html code
- [x] ensure that the search bar will always show "Enter weapon name..." when blank
- [x] ensure that all weapons that are not similar in name to whatever the user types in is display hidden
- [x] all weapons should still appear after deleting all characters from the search bar
- [x] have the search bar takes the entire width of the container
- [x] remove any unnecessary css rules and remove any console.logs
