### ISSUE TITLE
Issue 3: User can click more details about each weapon in BOTW

### ISSUE THREAD

**Issue by edtan094** [edtan094/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click more details about each weapon in BOTW

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user would like to know more about each weapon, they can simply click on the the card of the weapon and it will direct them to another page which will show them a brief description of the weapon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90667339/148289053-0571fec6-a8c2-421d-a1a4-f7e0ece86a93.png)
![image](https://user-images.githubusercontent.com/90667339/148289120-d3124ecb-f4c5-498c-83a8-6fe527b3782f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a search icon on the top right of the top
- [x] create a data variable in data.js with the following property key: view, saved
- [x] ensure that if the user clicks on the green block of a weapon, it directs them to the appropriate detail page for that item
- [x] view swap from the home page to the details page whenever the user clicks on the weapon
- [x] the user should be able to refresh in the details page and not lose their page
- [x] ensure the user can go back to the search page by clicking the search button
- [x] remove any console.log and unnecessary css styling
