### ISSUE TITLE
Issue 4: User can save each weapon to list to see for later

### ISSUE THREAD

**Issue by edtan094** [edtan094/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save each weapon to list to see for later

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user wants to save a weapon to view for later again, they may do so by hitting the save button which will save this weapon to be viewed later on the saved page  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90667339/148290430-90351512-b0ee-4738-bee3-fb130e781348.png)
![image](https://user-images.githubusercontent.com/90667339/148290347-093bf50f-a96d-4dd6-9381-062d76fda5fd.png)
![image](https://user-images.githubusercontent.com/90667339/148290369-a0b3b558-33c5-4cda-9e53-10212383dfc7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a save button for the user to view and click when they visit the details page of each weapon
- [x] once the user hits save, ensure that the object in data.clicked is pushed to the saved array
- [x] ensure that the saved page is generated using the data from the saved array within data
- [x] ensure that the saved page looks just like the home search page
- [x] remove and unnecessary css and console.log
