### ISSUE TITLE
Issue 5: User can delete a saved weapon from list

### ISSUE THREAD

**Issue by edtan094** [edtan094/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a saved weapon from list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user would like to delete a saved entry, they can do so by hitting the delete button 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90667339/148290574-ffea73c9-be5d-41e5-995a-dfe5597602ce.png)
![image](https://user-images.githubusercontent.com/90667339/148290609-5ede0ecb-87b3-4792-9aaf-505ecab62210.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a delete button feature for the user to see on weapons the user has previously saved
- [x] ensure that once the delete button is hit by the user, the entry from data.saved is removed
- [x] ensure that the weapon is removed from the saved list even after refreshing the page
- [x] remove and unnecessary css and console.log
